[WIP] glass: add poll service
aquarist-labs/aquarium pull request #197
Opened 2021-02-22 09:50 UTC by s0nea

Fixes: https://github.com/aquarist-labs/aquarium/issues/185
Signed-off-by: Tatjana Dehler <tdehler@suse.com>

2021-02-22 14:56 UTC, Devp00l submitted a review, later dismissed
LGTM so far :D

2021-02-25 11:37 UTC, votdev requested changes
Works, but need some adaptions.

2021-02-25 11:37 UTC, votdev commented on src/glass/src/app/pages/deployment-page/deployment-page.component.ts
> +            Object.values(hostDevices).forEach((v) => {
I think this should also work.
```suggestion
            let hasDevices = Object.values(hostDevices).some((v) => v.devices.length);
```

2021-02-25 11:37 UTC, votdev commented on src/glass/src/app/pages/deployment-page/deployment-page.component.ts
> +      .pipe(this.pollService.poll((res) => !res, undefined, 'Failed to deploy disks.'))
We are using `devices` allover the page, so we should use it here, too.
```suggestion
      .pipe(this.pollService.poll((res) => !res, undefined, 'Failed to deploy devices.'))
```

2021-02-25 16:23 UTC, votdev requested changes
I would also suggest to move the service to `/shared/services` because it is not related to API only.

2021-02-25 16:23 UTC, votdev commented on src/glass/src/app/pages/deployment-page/deployment-page.component.ts
> +          (hostDevices) => Object.values(hostDevices).some((v) => v.devices.length),
```suggestion
          (hostDevices): boolean => !Object.values(hostDevices).some((v) => v.devices.length),
```

2021-02-26 09:20 UTC, s0nea commented
> I would also suggest to move the service to `/shared/services` because it is not related to API only.

Yeah... I put it into the `api` folder because the service can't be used outside of it... But if there was/will be a poll API endpoint, it probably makes sense to move it outside.

2021-02-26 10:06 UTC, votdev approved these changes

2021-02-26 10:06 UTC, merged