doc: adding hackweek proposal
aquarist-labs/aquarium pull request #279
Opened 2021-03-10 11:47 UTC by asettle

Signed-off-by: Alexandra Settle <asettle@suse.com>

2021-03-10 11:52 UTC, jhesketh submitted a review, later dismissed
Cool, lgtm!

2021-03-10 15:39 UTC, jecluis approved these changes

2021-03-11 02:12 UTC, ml8mr submitted a review, later dismissed

2021-03-11 08:18 UTC, tserong requested changes
A couple of little nits, otherwise looks excellent

2021-03-11 08:18 UTC, tserong commented on doc/spec/hackweek-proposal.md
> +We are currently in Phrase 2 (Milestone 2) of the project where we are actively developing how to deploy a multi-node setup. Our goals:
s/Phrase/Phase/

2021-03-11 08:18 UTC, tserong commented on doc/spec/hackweek-proposal.md
> +If you consider yourself non-technical, but want to get involved another way:
Can we say something other than "non-technical" here, or even just strip this back to "If you want to get involved in another way"?

2021-03-11 09:32 UTC, tserong approved these changes

2021-03-11 09:32 UTC, merged