gravel/glass: add option to configure ntp at initial deployment
aquarist-labs/aquarium pull request #334
Opened 2021-03-26 13:46 UTC by s0nea

- **gravel: add PUT-method to set NTP**: Add a PUT-method to the orch endpoint in order to set the NTP server for a node.
- **glass: add option to configure NTP on initial node**

![Screenshot_2021-03-26_14-16-41](https://user-images.githubusercontent.com/8761082/112637619-a3134e00-8e3e-11eb-8dea-24b7bef8f053.png)
![Screenshot_2021-03-26_14-16-53](https://user-images.githubusercontent.com/8761082/112637401-69424780-8e3e-11eb-96f1-666ec9a435ee.png)

Signed-off-by: Tatjana Dehler <tdehler@suse.com>

2021-03-27 21:01 UTC, jecluis requested changes
I'm on board with the approach, but I think we need to do some error checking and additional sanity checks.

2021-03-29 07:54 UTC, votdev requested changes

2021-03-29 07:54 UTC, votdev commented on src/glass/src/app/pages/install-config-page/install-config-page.component.scss
> +  .mat-card {
The `Next` button should be colored using the primary color like it is done for all buttons that guide the user through the installer.

```
Index: src/glass/src/app/pages/install-config-page/install-config-page.component.scss
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/glass/src/app/pages/install-config-page/install-config-page.component.scss b/src/glass/src/app/pages/install-config-page/install-config-page.component.scss
--- a/src/glass/src/app/pages/install-config-page/install-config-page.component.scss	(revision 0906617794bc669f1771f048e81406451b75c698)
+++ b/src/glass/src/app/pages/install-config-page/install-config-page.component.scss	(date 1617004304085)
@@ -9,7 +9,7 @@
   background-repeat: no-repeat;
   background-position: center center;
 
-  .mat-card {
+  ::ng-deep .mat-card {
     width: 50%;
     @extend .glass-color-theme-white;
 
@@ -17,7 +17,7 @@
       margin-left: unset;
     }
 
-    ::ng-deep .mat-card.selected {
+    .mat-card.selected {
       border: 1px solid $glass-color-accent;
       color: $glass-color-white;
       background-color: rgba($glass-color-accent, 0.1);
@@ -33,7 +33,7 @@
       }
     }
 
-    ::ng-deep .mat-card {
+    .mat-card {
       border: 1px solid transparent;
       color: $eos-bc-gray-300;
 
@@ -51,5 +51,9 @@
         }
       }
     }
+
+    .mat-button {
+      @extend .glass-color-theme-primary;
+    }
   }
 }
```

2021-03-30 16:18 UTC, votdev submitted a review, later dismissed

2021-03-30 17:12 UTC, votdev approved these changes

2021-03-30 17:41 UTC, jecluis approved these changes

2021-03-30 17:43 UTC, merged