gravel: fix inventory gathering, and speed up device probing
aquarist-labs/aquarium pull request #476
Opened 2021-05-05 07:48 UTC by jecluis

Signed-off-by: Joao Eduardo Luis \<joao@suse.com>

2021-05-05 11:14 UTC, jhesketh requested changes
Perhaps a nit.

Also, are we ready to require tests going forward?

2021-05-05 11:14 UTC, jhesketh commented on src/gravel/controllers/resources/inventory_sub.py
> +        self._registry.remove(self)
Seems odd for Inventory to add the subscriber to the inventory but of the subscriber itself to unsubscribe. I think NodeMgr should call back to the Inventory to remove any subs.

2021-05-12 10:16 UTC, jecluis commented
@jhesketh addressed, repushed. no tests though, I'll have to figure out how to write those and, tbh, I'd rather have this in soon instead of waiting for them.

2021-05-12 11:30 UTC, jhesketh requested changes
The change looks good, but we need to choose here how strict we want to be with requiring tests going forward.

From our discussions it is my impression that we want to require at least some level of testing. This does mean things will move slower and things may be held up more, but I also believe that is the only way we're going to make any progress on growing our test coverage. As such I'm marking this as a "requests changes", but should others disagree the change still looks good and I'm happy for it to merge.

2021-05-12 19:09 UTC, mgfritch approved these changes
lgtm!

2021-05-12 19:09 UTC, mgfritch commented on src/gravel/tests/unit/controllers/resources/test_inventory.py
> +        operating_system="fancything",
fancy!

2021-05-12 19:15 UTC, merged

2021-05-12 23:45 UTC, jhesketh reviewed
Awesome, thanks for adding a test :-)