[doc]: update doc for python3.8 and pyenv for issue [#440]
aquarist-labs/aquarium pull request #490
Opened 2021-05-11 09:44 UTC by AvengerMoJo

Update the doc to include pyenv in setup script. 
Fixes: [#440]

Signed-off-by: Alex Lau (AvengerMoJo) <alau@suse.com>

2021-05-11 10:51 UTC, asettle requested changes
Few nits :) looks good!

2021-05-11 10:51 UTC, asettle commented on doc/from-zero-to-hacking.md
> +   help you setup an alternative python environment. If pyenv is already
```suggestion
   Aquarium requires python3.8+ to run successfully. If your host distribution does
   not support python3.8+ offically yet, our setup script provides pyenv to
   help you setup an alternative python environment. If pyenv already

2021-05-11 10:51 UTC, asettle commented on doc/from-zero-to-hacking.md
> +    `--pyenv-python 3.8.8`
```suggestion
   exists in`$HOME/.pyenv/` , the script will try to reuse your setup. Regardless,
   you will need to provide the python version. For example:
    `--pyenv-python 3.8.8`

2021-05-11 18:25 UTC, kshtsk commented
jenkins run leap

2021-05-12 13:28 UTC, kshtsk commented
@asettle are your change requests addressed?

2021-05-12 13:54 UTC, asettle approved these changes

2021-05-13 06:57 UTC, merged