ceph.git: update to the latest ceph pacific
aquarist-labs/aquarium pull request #513
Opened 2021-05-25 23:42 UTC by mgfritch

- Ceph Pacific v16.2.4 + latest backports
- includes upstream backport of:
  - ceph/ceph#40411
  - ceph/ceph#40555
  - ceph/ceph#40463

Resolves: #389
Signed-off-by: Michael Fritch <mfritch@suse.com>

## Checklist
- [ ] References issues, create if required
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins test tumbleweed`
- `jenkins run tumbleweed`
- `jenkins test leap`
- `jenkins run leap`

</details>

2021-05-28 06:42 UTC, jhesketh approved these changes

2021-06-01 05:28 UTC, jecluis requested changes
I'm having troubles bootstrapping the cluster when using the new HEAD. Holding off on this PR until I get to the bottom of it.

```
[ERROR] 2021-06-01T05:22:24 -- deployment -- bootstrap finish error: error bootstrapping: rc = 1
[INFO ] 2021-06-01T05:22:24 -- mgr -- finish deployment config
[DEBUG] 2021-06-01T05:22:25 -- deployment -- deployment > assimilating devices
[ERROR] 2021-06-01T05:22:25 -- ceph -- error running command: rc = -2, reason = No orchestrator configured (try `ceph orch set backend`)
[ERROR] 2021-06-01T05:22:25 -- deployment -- unable to assimilate devices
[ERROR] 2021-06-01T05:22:25 -- deployment -- No orchestrator configured (try `ceph orch set backend`)
Traceback (most recent call last):
  File "/srv/aquarium/src/./gravel/controllers/nodes/deployment.py", line 426, in _assimilate_devices
    orch.assimilate_all_devices()
  File "/srv/aquarium/src/./gravel/controllers/orch/orchestrator.py", line 59, in assimilate_all_devices
    res = self.call(cmd)
  File "/srv/aquarium/src/./gravel/controllers/orch/orchestrator.py", line 42, in call
    return self.cluster.call(cmd)
  File "/srv/aquarium/src/./gravel/controllers/orch/ceph.py", line 193, in call
    return self.ceph.mgr(cmd)
  File "/srv/aquarium/src/./gravel/controllers/orch/ceph.py", line 183, in mgr
    return self._cmd(self.cluster.mgr_command, cmd)
  File "/srv/aquarium/src/./gravel/controllers/orch/ceph.py", line 167, in _cmd
    raise CephCommandError(outstr, rc=rc)
gravel.controllers.orch.ceph.CephCommandError: No orchestrator configured (try `ceph orch set backend`)
```

Additionally,

```
[ceph: root@foobar /]# ceph orch set backend cephadm
Error EINVAL: Module 'cephadm' is not enabled. 
 Run `ceph mgr module enable cephadm` to enable.
```

2021-06-01 06:33 UTC, jecluis commented
Depends on https://github.com/aquarist-labs/aquarium/pull/526 being merged.

2021-06-01 16:19 UTC, jecluis approved these changes

2021-06-01 16:19 UTC, merged