glass: show disk solution during installer
aquarist-labs/aquarium pull request #534
Opened 2021-06-03 04:41 UTC by jecluis

Instead of just showing the list of available devices, show instead the proposed solution.

Signed-off-by: Joao Eduardo Luis \<joao@suse.com>

2021-06-07 07:53 UTC, votdev requested changes

2021-06-07 07:53 UTC, votdev commented on src/glass/src/app/pages/install-wizard/steps/local-devices-step/local-devices-step.component.ts
> +          entry.useAs = 'system';
```suggestion
          entry.useAs = translate(TEXT('System'));
```

2021-06-07 07:53 UTC, votdev commented on src/glass/src/app/pages/install-wizard/steps/local-devices-step/local-devices-step.component.ts
> +          entry.useAs = 'storage';
```suggestion
          entry.useAs = translate(TEXT('Storage'));
```

2021-06-07 07:53 UTC, votdev commented on src/glass/src/app/pages/install-wizard/steps/local-devices-step/local-devices-step.component.ts
> +    let typeStr = 'unknown';
```suggestion
    let typeStr = translate(TEXT('Unknown'));
```

2021-06-07 07:53 UTC, votdev commented on src/glass/src/app/pages/install-wizard/steps/local-devices-step/local-devices-step.component.ts
> +      typeStr = 'HDD';
```suggestion
      typeStr = translate(TEXT('HDD'));
```

2021-06-07 07:53 UTC, votdev commented on src/glass/src/app/pages/install-wizard/steps/local-devices-step/local-devices-step.component.ts
> +      typeStr = 'SSD';
```suggestion
      typeStr = translate(TEXT('SSD'));
```

2021-06-07 07:53 UTC, votdev commented on src/glass/src/app/pages/install-wizard/steps/local-devices-step/local-devices-step.component.ts
> +      useAs: 'N/A',
```suggestion
      useAs: translate(TEXT('N/A')),
```

2021-06-08 14:19 UTC, jecluis commented
jenkins run tumbleweed

2021-06-08 15:05 UTC, votdev approved these changes

2021-06-08 15:05 UTC, merged