glass: Updates language assets
aquarist-labs/aquarium pull request #545
Opened 2021-06-07 07:52 UTC by Devp00l

Signed-off-by: Stephan Müller <smueller@suse.com>

## Checklist
- [ ] References issues, create if required
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins test tumbleweed`
- `jenkins run tumbleweed`
- `jenkins test leap`
- `jenkins run leap`

</details>

2021-06-07 10:06 UTC, votdev requested changes

2021-06-07 10:06 UTC, votdev commented on src/glass/src/app/i18n.helper.ts
> +  en_US: TEXT('English'),
I'm not sure if we should translate them. Imagine you accidentally switch to Chinese language  and then `Deutsch` is displayed in Chinese letters. Each language should be hard-coded:
```
en_US => English
de_DE => Deutsch
zh_CN (Chinese) => 中國人
zh_TW (Taiwanese) => 台灣
```
@AvengerMoJo Please correct my Google translations.

2021-06-07 17:05 UTC, votdev commented on src/glass/src/app/i18n.helper.ts
> +  en_US: TEXT('English'),
According to @AvengerMoJo you should use
```
zh_CN (Simplified) => 简体中文
zh_TW (Traditional) => 繁體中文
```

2021-06-08 03:50 UTC, AvengerMoJo reviewed
It does not allow me to comment before I review I believe.
```
zh_CN (Simplified) => 简体中文
zh_TW (Traditional) => 繁體中文
```
Let's use the above translation

2021-06-11 06:14 UTC, AvengerMoJo commented
jenkins test tumbleweed

2021-06-11 06:18 UTC, AvengerMoJo approved these changes

2021-06-14 09:15 UTC, votdev submitted a review, later dismissed

2021-06-14 09:54 UTC, s0nea commented on src/glass/src/assets/i18n/de_DE.json
> +   "Authentication Token": "Authentifizierungstoken",
```suggestion
   "Authentication Token": "Authentifizierungsschlüssel",
```

2021-06-14 09:54 UTC, s0nea commented on src/glass/src/assets/i18n/de_DE.json
> +   "CPU Load": "CPU Load",
Why not keeping "CPU-Auslastung"?

2021-06-14 09:54 UTC, s0nea commented on src/glass/src/assets/i18n/de_DE.json
> +   "CephFS Service": "CephFS Bedienung",
```suggestion
   "CephFS Service": "CephFS-Dienst",
```

2021-06-14 09:54 UTC, s0nea commented on src/glass/src/assets/i18n/de_DE.json
> +   "Dashboard": "Dashboard",
Can't we just leave it empty so it falls back to the English translation?

2021-06-14 09:54 UTC, s0nea commented on src/glass/src/assets/i18n/de_DE.json
> +   "System Information": "System Information",
```suggestion
   "System Information": "Systeminformationen",
```

2021-06-14 09:54 UTC, s0nea commented on src/glass/src/assets/i18n/de_DE.json
> +   "Vendor": "Lieferant",
```suggestion
   "Vendor": "Anbieter",
```

2021-06-14 10:12 UTC, jecluis commented
@votdev is this being merged in the next few hours? I'd like to cut M4 soon.

2021-06-14 10:19 UTC, s0nea approved these changes

2021-06-14 11:10 UTC, votdev approved these changes

2021-06-14 11:21 UTC, s0nea approved these changes

2021-06-14 11:44 UTC, jecluis commented
jenkins run tumbleweed

2021-06-14 12:12 UTC, merged