NTP configuration follower nodes
aquarist-labs/aquarium pull request #558
Opened 2021-06-08 17:44 UTC by s0nea

## Checklist
- [ ] References issues, create if required
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins test tumbleweed`
- `jenkins run tumbleweed`
- `jenkins test leap`
- `jenkins run leap`

</details>

2021-06-09 15:12 UTC, kshtsk commented
jenkins test opensuse

2021-06-09 19:04 UTC, jecluis requested changes
generally looks good to me, but a few things should be addressed.

2021-06-10 07:51 UTC, s0nea commented on src/gravel/controllers/nodes/ntp.py
> +        subprocess.check_output(restart_cmd, stderr=subprocess.PIPE)
Oh, yes, makes totally sense. I'll update the PR.

2021-06-11 07:31 UTC, jecluis approved these changes

2021-06-11 07:51 UTC, votdev approved these changes

2021-06-11 07:51 UTC, merged